"""added fields to customer

Revision ID: b9f36a91fd25
Revises: 86e47c3979ad
Create Date: 2023-04-21 15:59:38.101185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9f36a91fd25'
down_revision = '86e47c3979ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('birthday', sa.Date(), nullable=True))
    op.add_column('customer', sa.Column('photo_path', sa.String(length=255), nullable=True))
    op.add_column('customer', sa.Column('email', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'email')
    op.drop_column('customer', 'photo_path')
    op.drop_column('customer', 'birthday')
    # ### end Alembic commands ###
