"""not_nullable_muscle_id

Revision ID: fdb694cf041a
Revises: fd6e94e62290
Create Date: 2023-04-16 09:53:34.321511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdb694cf041a'
down_revision = 'fd6e94e62290'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercise', 'muscle_group_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercise', 'muscle_group_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
