"""superset_id column

Revision ID: 642ff7c24e01
Revises: b9f36a91fd25
Create Date: 2023-04-25 17:11:30.680339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642ff7c24e01'
down_revision = 'b9f36a91fd25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercisesontraining', sa.Column('superset_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercisesontraining', 'superset_id')
    # ### end Alembic commands ###
