"""extend training plan

Revision ID: 7db71b08defe
Revises: 065602626fd6
Create Date: 2023-04-17 18:20:45.203722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db71b08defe'
down_revision = '065602626fd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainingplan', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('trainingplan', sa.Column('set_rest', sa.Integer(), nullable=True))
    op.add_column('trainingplan', sa.Column('exercise_rest', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainingplan', 'exercise_rest')
    op.drop_column('trainingplan', 'set_rest')
    op.drop_column('trainingplan', 'notes')
    # ### end Alembic commands ###
