"""training plan cascade delete

Revision ID: 8e9438cf8eed
Revises: dd6aa2cf5ddb
Create Date: 2023-07-18 09:50:47.444747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e9438cf8eed'
down_revision = 'dd6aa2cf5ddb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trainingplan', 'customer_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.drop_constraint('trainingplan_customer_id_fkey', 'trainingplan', type_='foreignkey')
    op.create_foreign_key(None, 'trainingplan', 'customer', ['customer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trainingplan', type_='foreignkey')
    op.create_foreign_key('trainingplan_customer_id_fkey', 'trainingplan', 'customer', ['customer_id'], ['id'])
    op.alter_column('trainingplan', 'customer_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
