"""customer cascade delete

Revision ID: c79657831349
Revises: 04dea0019dc0
Create Date: 2023-07-22 08:19:13.850735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c79657831349'
down_revision = '04dea0019dc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'coach_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.drop_constraint('customer_coach_id_fkey', 'customer', type_='foreignkey')
    op.create_foreign_key(None, 'customer', 'coach', ['coach_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.create_foreign_key('customer_coach_id_fkey', 'customer', 'coach', ['coach_id'], ['id'])
    op.alter_column('customer', 'coach_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
