"""insert exercises

Revision ID: 065602626fd6
Revises: fdb694cf041a
Create Date: 2023-04-17 12:13:10.408063

"""
from alembic import op
from sqlalchemy.orm import Session
from src.gym.models import MuscleGroup, Exercise

# revision identifiers, used by Alembic.
revision = '065602626fd6'
down_revision = 'fdb694cf041a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    muscle_groups = (
        MuscleGroup(name="Грудь"),
        MuscleGroup(name="Бицепс"),

        MuscleGroup(name="Спина"),
        MuscleGroup(name="Трицепс"),

        MuscleGroup(name="Ноги")
    )

    session = Session(bind=op.get_bind())

    session.bulk_save_objects(muscle_groups)
    session.commit()

    chest = session.query(MuscleGroup).filter(MuscleGroup.name == "Грудь").first()
    biceps = session.query(MuscleGroup).filter(MuscleGroup.name == "Бицепс").first()
    back = session.query(MuscleGroup).filter(MuscleGroup.name == "Спина").first()
    triceps = session.query(MuscleGroup).filter(MuscleGroup.name == "Трицепс").first()
    legs = session.query(MuscleGroup).filter(MuscleGroup.name == "Ноги").first()

    exercises = (
        Exercise(
            name='Жим штанги лежа',
            muscle_group_id=str(chest.id)
        ),
        Exercise(
            name='Разводка с гантелями',
            muscle_group_id=str(chest.id)
        ),
        Exercise(
            name='Сведения в кроссовере',
            muscle_group_id=str(chest.id)
        ),
        Exercise(
            name='Подъем штанги на бицепс',
            muscle_group_id=str(biceps.id)
        ),
        Exercise(
            name='Сгибания Молот',
            muscle_group_id=str(biceps.id)
        ),

        Exercise(
            name='Подтягивания',
            muscle_group_id=str(back.id)
        ),
        Exercise(
            name='Тяга штанги в наклоне',
            muscle_group_id=str(back.id)
        ),
        Exercise(
            name='Пулловер с верхнего блока',
            muscle_group_id=str(back.id)
        ),
        Exercise(
            name='Жим штанги узким хватом',
            muscle_group_id=str(triceps.id)
        ),
        Exercise(
            name='Разгибания с верхнего блока',
            muscle_group_id=str(triceps.id)
        ),

        Exercise(
            name='Приседания со штангой',
            muscle_group_id=str(legs.id)
        ),
        Exercise(
            name='Жим платформы ногами',
            muscle_group_id=str(legs.id)
        ),
        Exercise(
            name='Сгибания ногами сидя',
            muscle_group_id=str(legs.id)
        ),
        Exercise(
            name='Разгибания ногами лежа',
            muscle_group_id=str(legs.id),
        ),
        Exercise(
            name='Становая тяга на прямых ногах',
            muscle_group_id=str(legs.id)
        )
    )

    session.bulk_save_objects(exercises)
    session.commit()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
