"""add relationship with coach

Revision ID: dd6aa2cf5ddb
Revises: 102b9ad91d88
Create Date: 2023-05-29 21:18:58.620919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd6aa2cf5ddb'
down_revision = '102b9ad91d88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach', sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=True))
    op.add_column('customer', sa.Column('coach_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'customer', 'coach', ['coach_id'], ['id'])
    op.add_column('exercise', sa.Column('coach_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'exercise', 'coach', ['coach_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercise', type_='foreignkey')
    op.drop_column('exercise', 'coach_id')
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.drop_column('customer', 'coach_id')
    op.drop_column('coach', 'gender')
    # ### end Alembic commands ###
