"""add ordering field

Revision ID: 7b800cccb3e9
Revises: 642ff7c24e01
Create Date: 2023-05-28 07:39:37.210557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b800cccb3e9'
down_revision = '642ff7c24e01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercisesontraining', sa.Column('ordering', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercisesontraining', 'ordering')
    # ### end Alembic commands ###
