"""remove relationship with user

Revision ID: acd2c4c6d3a0
Revises: 7b800cccb3e9
Create Date: 2023-05-29 21:10:48.818870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acd2c4c6d3a0'
down_revision = '7b800cccb3e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customer_user_id_fkey', 'customer', type_='foreignkey')
    op.drop_column('customer', 'user_id')
    op.drop_constraint('exercise_user_id_fkey', 'exercise', type_='foreignkey')
    op.drop_column('exercise', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('exercise_user_id_fkey', 'exercise', 'user', ['user_id'], ['id'])
    op.add_column('customer', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('customer_user_id_fkey', 'customer', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
