"""diet cascade delete

Revision ID: 22bc1d04e7de
Revises: c79657831349
Create Date: 2023-07-25 09:23:48.525625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '22bc1d04e7de'
down_revision = 'c79657831349'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dietontrainingplan', 'diet_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('dietontrainingplan', 'training_plan_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.drop_constraint('dietontrainingplan_diet_id_fkey', 'dietontrainingplan', type_='foreignkey')
    op.drop_constraint('dietontrainingplan_training_plan_id_fkey', 'dietontrainingplan', type_='foreignkey')
    op.create_foreign_key(None, 'dietontrainingplan', 'trainingplan', ['training_plan_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'dietontrainingplan', 'diet', ['diet_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dietontrainingplan', type_='foreignkey')
    op.drop_constraint(None, 'dietontrainingplan', type_='foreignkey')
    op.create_foreign_key('dietontrainingplan_training_plan_id_fkey', 'dietontrainingplan', 'trainingplan', ['training_plan_id'], ['id'])
    op.create_foreign_key('dietontrainingplan_diet_id_fkey', 'dietontrainingplan', 'diet', ['diet_id'], ['id'])
    op.alter_column('dietontrainingplan', 'training_plan_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('dietontrainingplan', 'diet_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
