"""added user columns

Revision ID: f6cfdccd4b38
Revises: 9708e520e957
Create Date: 2023-04-03 18:01:13.007224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6cfdccd4b38'
down_revision = '9708e520e957'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('birthday', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('photo_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'photo_path')
    op.drop_column('user', 'birthday')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
