"""muscle_group_model

Revision ID: fd6e94e62290
Revises: eec98af1400c
Create Date: 2023-04-16 08:51:05.550411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd6e94e62290'
down_revision = 'eec98af1400c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('musclegroup',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_musclegroup_id'), 'musclegroup', ['id'], unique=False)
    op.add_column('exercise', sa.Column('muscle_group_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'exercise', 'musclegroup', ['muscle_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercise', type_='foreignkey')
    op.drop_column('exercise', 'muscle_group_id')
    op.drop_index(op.f('ix_musclegroup_id'), table_name='musclegroup')
    op.drop_table('musclegroup')
    # ### end Alembic commands ###
