"""rename column to diet_id

Revision ID: eec98af1400c
Revises: 3640e8a23129
Create Date: 2023-04-14 09:51:58.337421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eec98af1400c'
down_revision = '3640e8a23129'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dietontrainingplan', sa.Column('diet_id', sa.UUID(), nullable=False))
    op.drop_constraint('dietontrainingplan_nutrition_id_fkey', 'dietontrainingplan', type_='foreignkey')
    op.create_foreign_key(None, 'dietontrainingplan', 'diet', ['diet_id'], ['id'])
    op.drop_column('dietontrainingplan', 'nutrition_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dietontrainingplan', sa.Column('nutrition_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'dietontrainingplan', type_='foreignkey')
    op.create_foreign_key('dietontrainingplan_nutrition_id_fkey', 'dietontrainingplan', 'diet', ['nutrition_id'], ['id'])
    op.drop_column('dietontrainingplan', 'diet_id')
    # ### end Alembic commands ###
