"""add fcm token for users

Revision ID: 96e443d19c1b
Revises: caac18da2dbf
Create Date: 2023-12-16 16:39:06.430313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e443d19c1b'
down_revision = 'caac18da2dbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach', sa.Column('fcm_token', sa.String(length=255), nullable=False))
    op.add_column('customer', sa.Column('fcm_token', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'fcm_token')
    op.drop_column('coach', 'fcm_token')
    # ### end Alembic commands ###
