"""coach cascade deletion

Revision ID: caac18da2dbf
Revises: 39597fa7b57c
Create Date: 2023-09-21 14:17:42.242620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caac18da2dbf'
down_revision = '39597fa7b57c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('exercise_coach_id_fkey', 'exercise', type_='foreignkey')
    op.create_foreign_key(None, 'exercise', 'coach', ['coach_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercise', type_='foreignkey')
    op.create_foreign_key('exercise_coach_id_fkey', 'exercise', 'coach', ['coach_id'], ['id'])
    # ### end Alembic commands ###
