"""add fcm token for coach

Revision ID: ab8ce6149543
Revises: d703a0b31a04
Create Date: 2023-12-13 18:49:30.032098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab8ce6149543'
down_revision = 'd703a0b31a04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach', sa.Column('fcm_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coach', 'fcm_token')
    # ### end Alembic commands ###
