"""add fcm token for customer

Revision ID: d703a0b31a04
Revises: caac18da2dbf
Create Date: 2023-12-13 08:20:57.724341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd703a0b31a04'
down_revision = 'caac18da2dbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('fcm_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'fcm_token')
    # ### end Alembic commands ###
