"""remove product table

Revision ID: d64255d17b5a
Revises: fbdf8cb21fa3
Create Date: 2024-09-02 19:32:22.546515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd64255d17b5a'
down_revision = 'fbdf8cb21fa3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_id', table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('product_type', postgresql.ENUM('GRAM', 'MILLILITER', 'PORTION', name='producttype'), autoincrement=False, nullable=False),
    sa.Column('proteins', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fats', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('carbs', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('calories', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vendor_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('coach_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['coach.id'], name='product_coach_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='product_pkey')
    )
    op.create_index('ix_product_id', 'product', ['id'], unique=False)
    # ### end Alembic commands ###
