"""customer telegram username

Revision ID: 37c8848d06e6
Revises: ebc6d52a6622
Create Date: 2024-03-19 20:43:25.103027

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37c8848d06e6'
down_revision = 'ebc6d52a6622'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('telegram_username', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_customer_telegram_username'), 'customer', ['telegram_username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_telegram_username'), table_name='customer')
    op.drop_column('customer', 'telegram_username')
    # ### end Alembic commands ###
