"""add calories column

Revision ID: 8c8b444d1a93
Revises: 08d8c7b46ca4
Create Date: 2024-08-22 12:43:59.701357

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c8b444d1a93'
down_revision = '08d8c7b46ca4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diet', sa.Column('calories', sa.Integer(), nullable=False))
    op.alter_column('meal', 'total_fats', existing_type=sa.INTEGER(), nullable=False)
    op.alter_column('meal', 'consumed_fats', existing_type=sa.INTEGER(), nullable=True)
    op.alter_column('meal', 'total_carbs', existing_type=sa.INTEGER(), nullable=False)
    op.alter_column('meal', 'consumed_carbs', existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meal', 'consumed_carbs', existing_type=sa.INTEGER(), nullable=False)
    op.alter_column('meal', 'total_carbs', existing_type=sa.INTEGER(), nullable=True)
    op.alter_column('meal', 'consumed_fats', existing_type=sa.INTEGER(), nullable=False)
    op.alter_column('meal', 'total_fats', existing_type=sa.INTEGER(), nullable=True)
    op.drop_column('diet', 'calories')
    # ### end Alembic commands ###
