"""customer phone number

Revision ID: d32f5ba7fb5c
Revises: ebc6d52a6622
Create Date: 2024-03-18 19:39:02.267040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd32f5ba7fb5c'
down_revision = 'ebc6d52a6622'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone_number', sa.String(length=100), nullable=True))
    op.drop_index('ix_customer_username', table_name='customer')
    op.create_index(op.f('ix_customer_username'), 'customer', ['username'], unique=True)
    op.create_index(op.f('ix_customer_phone_number'), 'customer', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('invited_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_customer_phone_number'), table_name='customer')
    op.drop_index(op.f('ix_customer_username'), table_name='customer')
    op.create_index('ix_customer_username', 'customer', ['username'], unique=False)
    # ### end Alembic commands ###
