"""create diet day table

Revision ID: fbdf8cb21fa3
Revises: e84676267e77
Create Date: 2024-08-23 14:57:35.539948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fbdf8cb21fa3'
down_revision = 'e84676267e77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dietday',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.DateTime(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('breakfast', sa.JSON(), nullable=True),
    sa.Column('lunch', sa.JSON(), nullable=True),
    sa.Column('dinner', sa.JSON(), nullable=True),
    sa.Column('snacks', sa.JSON(), nullable=True),
    sa.Column('diet_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['diet_id'], ['diet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('diet', 'breakfast')
    op.drop_column('diet', 'consumed_proteins')
    op.drop_column('diet', 'consumed_calories')
    op.drop_column('diet', 'lunch')
    op.drop_column('diet', 'consumed_fats')
    op.drop_column('diet', 'consumed_carbs')
    op.drop_column('diet', 'dinner')
    op.drop_column('diet', 'snacks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diet', sa.Column('snacks', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('diet', sa.Column('dinner', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('diet', sa.Column('consumed_carbs', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('diet', sa.Column('consumed_fats', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('diet', sa.Column('lunch', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('diet', sa.Column('consumed_calories', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('diet', sa.Column('consumed_proteins', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('diet', sa.Column('breakfast', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_table('dietday')
    # ### end Alembic commands ###
