"""plan to diets one to many

Revision ID: 4cc058789454
Revises: 37c8848d06e6
Create Date: 2024-06-30 12:58:44.569512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4cc058789454'
down_revision = '37c8848d06e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diet', sa.Column('training_plan_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'diet', 'trainingplan', ['training_plan_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'diet', type_='foreignkey')
    op.drop_column('diet', 'training_plan_id')
    # ### end Alembic commands ###
