"""add nutrition domain

Revision ID: 9543c57a9455
Revises: ea88688fea0d
Create Date: 2024-08-23 07:49:35.515720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9543c57a9455'
down_revision = 'ea88688fea0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('product_type', sa.Enum('GRAM', 'MILLILITER', 'PORTION', name='producttype'), nullable=False),
    sa.Column('proteins', sa.Integer(), nullable=False),
    sa.Column('fats', sa.Integer(), nullable=False),
    sa.Column('carbs', sa.Integer(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.add_column('diet', sa.Column('total_proteins', sa.Integer(), nullable=False))
    op.add_column('diet', sa.Column('consumed_proteins', sa.Integer(), nullable=True))
    op.add_column('diet', sa.Column('total_fats', sa.Integer(), nullable=False))
    op.add_column('diet', sa.Column('consumed_fats', sa.Integer(), nullable=True))
    op.add_column('diet', sa.Column('total_carbs', sa.Integer(), nullable=False))
    op.add_column('diet', sa.Column('consumed_carbs', sa.Integer(), nullable=True))
    op.add_column('diet', sa.Column('total_calories', sa.Integer(), nullable=False))
    op.add_column('diet', sa.Column('consumed_calories', sa.Integer(), nullable=True))
    op.add_column('diet', sa.Column('breakfast', sa.JSON(), nullable=True))
    op.add_column('diet', sa.Column('lunch', sa.JSON(), nullable=True))
    op.add_column('diet', sa.Column('dinner', sa.JSON(), nullable=True))
    op.add_column('diet', sa.Column('snacks', sa.JSON(), nullable=True))
    op.drop_column('diet', 'carbs')
    op.drop_column('diet', 'fats')
    op.drop_column('diet', 'proteins')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diet', sa.Column('proteins', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('diet', sa.Column('fats', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('diet', sa.Column('carbs', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('diet', 'snacks')
    op.drop_column('diet', 'dinner')
    op.drop_column('diet', 'lunch')
    op.drop_column('diet', 'breakfast')
    op.drop_column('diet', 'consumed_calories')
    op.drop_column('diet', 'total_calories')
    op.drop_column('diet', 'consumed_carbs')
    op.drop_column('diet', 'total_carbs')
    op.drop_column('diet', 'consumed_fats')
    op.drop_column('diet', 'total_fats')
    op.drop_column('diet', 'consumed_proteins')
    op.drop_column('diet', 'total_proteins')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
