"""remove diets on training plan model

Revision ID: ea88688fea0d
Revises: 4cc058789454
Create Date: 2024-07-14 10:58:38.978024

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea88688fea0d'
down_revision = '4cc058789454'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dietontrainingplan_id', table_name='dietontrainingplan')
    op.drop_table('dietontrainingplan')
    op.drop_column('customer', 'invited_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('invited_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_table('dietontrainingplan',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('diet_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('training_plan_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['diet_id'], ['diet.id'], name='dietontrainingplan_diet_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_plan_id'], ['trainingplan.id'], name='dietontrainingplan_training_plan_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='dietontrainingplan_pkey')
    )
    op.create_index('ix_dietontrainingplan_id', 'dietontrainingplan', ['id'], unique=False)
    # ### end Alembic commands ###
